baseurl = "/"
title = "Freifunk L端beck"
author = "Freifunk L端beck"
googleAnalytics = ""
defaultContentLanguage = "de"
paginate = 3

theme = "hugo-terrassa-theme"

[params]
    description = "Freifunk L端beck"
    favicon = "favicon.ico"
    logo = "images/ffhl-logo.png"

[params.hero]
    textColor = "" # Empty for default color

[params.cta] # Call To Action
    show = true
    cta = "Mitmachen"
    link = "mitmachen" # Relative URL

[params.separator] # Separators between sections on the home page
    show = true 

[menu]
  [[menu.main]]
    name = "Firmware"
    url = "https://firmware.luebeck.freifunk.net/wizard"
    weight = 100
    pre = "<i class='fas fa-external-link-alt'></i>"
  [[menu.main]]
    name = "Wiki"
    url = "https://wiki.luebeck.freifunk.net"
    weight = 101
    pre = "<i class='fas fa-external-link-alt'></i>"
  
  [[menu.main]]
    name = "Map"
    url = "https://map.luebeck.freifunk.net"
    weight = 102
    pre = "<i class='fas fa-external-link-alt'></i>"

  [[menu.main]]
    name = "Statistik"
    url = "https://monitor.luebeck.freifunk.net/"
    weight = 103
    pre = "<i class='fas fa-external-link-alt'></i>"

[params.posts]
    showAuthor = false
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"

[params.contact] # Contact info
    email = "info@luebeck.freifunk.net"
    Address = 'Nobreakspace, Fackenburger Allee 11 (23554, L端beck)'

[params.social]
    "fab fa-twitter" = "https://twitter.com/freifunkluebeck"
    "fab fa-git" = "https://git.luebeck.freifunk.net"
    #"fab fa-youtube" = "https://peertube.luebeck.freifunk.net"
    "fas fa-comments" = "https://matrix.to/#/!abaEXDFMmCWEivMGJF:matrix.org?via=matrix.org&via=matrix.eclabs.de&via=toppoint.de"

[params.languageSwitcher]
    show = false 

[params.copy]
    message = "Impressum"
    site = "impressum"

[languages]
    [languages.de]
        languageName = "de"
        weight = 1
        contentDir = "content/"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true