baseurl = "/"
title = "Freifunk Lübeck"
author = ""
googleAnalytics = ""
defaultContentLanguage = "de"
paginate = 3

theme = "hugo-terrassa-theme"

[params]
    description = "Freifunk Lübeck"
    favicon = "favicon.ico"
    logo = ""

[params.hero]
    textColor = "" # Empty for default color

[params.cta] # Call To Action
    show = true
    cta = "Mitmachen"
    link = "mitmachen" # Relative URL

[params.separator] # Separators between sections on the home page
    show = true 

[params.fa] # Font Awesome options
    version = "5.7.2"
    integrity = "sha384-0pzryjIRos8mFBWMzSSZApWtPl/5++eIfzYmTgBBmXYdhvxPc+XcFEk+zJwDgWbP"

# [params.form] # Contact form
#     netlify = true
#     action = "https://formspree.io/your@email.com"
#     method = "POST"
#     inputNameName = "name"
#     inputNameLabel = "Name"
#     inputNamePlaceholder = "Your name"
#     inputEmailName = "email"
#     inputEmailLabel = "Email"
#     inputEmailPlaceholder = "Your email"
#     inputMsgName = "message"
#     inputMsgLabel = "Write something"
#     inputMsgLength = 750
#     inputSubmitValue = "Send"

[params.posts]
    showAuthor = true
    showDate = true
    showTags = true
    dateFormat = "Monday, Jan, 2006"

[params.contact] # Contact info
    email = "info@luebeck.freifunk.net"
    chat = "#ffhl:matrix.org"
    chaturl = "https://matrix.to/#/!abaEXDFMmCWEivMGJF:matrix.org?via=matrix.org&via=matrix.eclabs.de&via=toppoint.de"
    address =  ""

[params.social]
    twitter = "https://twitter.com/freifunkluebeck"
    github = "https://github.com/freifunk-luebeck"
    gitlab = "https://gitlab.com/freifunk-luebeck"
    pinterest = ""
    youtube = ""
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""

# [params.copy] # Copyright
#     copy = "Impressum" # Empty for default content

[privacy]
    [privacy.googleAnalytics]
        anonymizeIP = true
        disable = true 
        respectDoNotTrack = true
        useSessionStorage = false
    [privacy.instagram]
        disable = true 
        simple = false
    [privacy.twitter]
        disable = true 
        enableDNT = true
        simple = false
    [privacy.vimeo]
        disable = true 
        simple = false
    [privacy.youtube]
        disable = true 
        privacyEnhanced = true

[params.languageSwitcher]
    show = false 

[languages]
    [languages.de]
        languageName = "de"
        weight = 1
        contentDir = "content/"
